name: Pull Request

on:
  push:
    branches: ["main"]
  pull_request: {}

jobs:
  changedfiles:
    name: Publish to docs
    runs-on: [ubuntu-latest]
    outputs:
      all: ${{ steps.changes.outputs.all}}
      sha: ${{ steps.changes.outputs.sha}}
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check Changes
        id: changes
        run: |
          echo "::set-output name=sha::$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=all::$(git diff --name-only main | xargs)"
  
  prdocs:
    name: PR to Docs Repo
    needs: changedfiles
    runs-on: [ubuntu-latest]
    steps:

      - name: Create pull Request
        run: |
          echo "${{needs.changedfiles.outputs.all}}"
          echo "${{needs.changedfiles.outputs.sha}}"
