name: Pull Request

on:
  push:
    branches: ["main"]
  pull_request: {}

jobs:
  changedfiles:
    name: Publish to docs
    runs-on: [ubuntu-latest]
    outputs:
      all: ${{ steps.changes.outputs.all}}
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check Changes
        id: changes
        run: |
          echo "::set-output name=all::$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs | grep -o "docs/")"
  
  prdocs:
    name: PR to Docs Repo
    # echo "${{needs.changedfiles.outputs.all}}"
    needs: changedfiles
    if: ${{needs.changedfiles.outputs.all}}
    runs-on: [ubuntu-latest]
    env:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      INPUT_SOURCE_FOLDER: "docs/output/"
      INPUT_DESTINATION_HEAD_BRANCH: ${{ github.event.pull_request.base.sha }}
      INPUT_USER_EMAIL: "michael.vienneau@colorado.edu"
      INPUT_USER_USER_NAME: "mvienneau"
      INPUT_DESITINATION_REPO: "moovfinancial/docs"
      INPUT_DESTINATION_FOLDER: "content/node/"
    runs:
      using: 'docker'
      image: 'Dockerfile'
